### ISSUE TITLE
Trying to compile with AVX and ccurl_compat

### ISSUE THREAD

**Issue by gagathos** [DLTcollab/dcurl#44]
Just to test. I am getting the following error:

```
Error: Dynamic Linking Error: ./libccurl.so: undefined symbol: PowSSE
    at new DynamicLibrary (/home/gagathos/iota-gpu-pow/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/home/gagathos/iota-gpu-pow/node_modules/ffi/lib/library.js:45:12)
    at module.exports (/home/gagathos/iota-gpu-pow/node_modules/ccurl.interface.js/index.js:83:26)
    at nodeAPI (/home/gagathos/iota-gpu-pow/remotePOW.js:56:3)
    at postHandler (/home/gagathos/iota-gpu-pow/remotePOW.js:43:6)
    at Layer.handle [as handle_request] (/home/gagathos/iota-gpu-pow/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gagathos/iota-gpu-pow/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/gagathos/iota-gpu-pow/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/gagathos/iota-gpu-pow/node_modules/express/lib/router/layer.js:95:5)
    at /home/gagathos/iota-gpu-pow/node_modules/express/lib/router/index.js:281:22
```

Does not show any failures on `make check`

**Comment by furuame** [comment]
Have you ever tried `make clean` before build AVX?

**Comment by gagathos** [comment]
I will try this week and get back to you.

**Comment by furuame** [comment]
@gagathos any progress?

**Comment by jserv** [comment]
Close since last contact. Once we have CI, it should be straightforward to locate such compilation problems.
