### ISSUE TITLE
Unable to pass multi-pow test item with FPGA accelerator

### ISSUE THREAD

**Issue by ajblane** [DLTcollab/dcurl#61]
Error messages with FPGA accelerator:

```
root@lampa:~/dcurl# make BUILD_FPGA_ACCEL=1 check                               
make: Warning: File 'mk/python.mk' has modification time 1534568560 s in the fue
  CC    build/curl.o                                                            
  CC    build/constants.o                                                       
  CC    build/trinary.o                                                         
  CC    build/dcurl.o                                                           
  CC    build/implcontext.o                                                     
  CC    build/pow_c.o                                                           
  CC    build/pow_fpga_accel.o                                                  
  CC    build/test-trinary.o                                                    
  LD    build/test-trinary                                                      
*** Validating build/test-trinary ***                                           
        [ Verified ]                                                            
  CC    build/test-curl.o                                                       
  LD    build/test-curl                                                         
*** Validating build/test-curl ***                                              
        [ Verified ]                                                            
  CC    build/test-dcurl.o                                                      
  LD    build/test-dcurl                                                        
*** Validating build/test-dcurl ***                                             
[  409.187196] Get interrupt                                                    
        [ Verified ]                                                            
  LD    build/libdcurl.so                                                       
*** Validating build/test-multi-pow ***                                         
[  413.727193] Get interrupt                                                    
[  413.745242] Get interrupt                                                    
[  413.992183] Get interrupt                                                    
[  414.190852] Get interrupt                                                    
[  414.291223] Get interrupt                                                    
[  414.386504] Get interrupt                                                    
[  414.517357] Get interrupt                                                    
Unhandled exception in thread started by <function call_dcurl at 0xb5a75300>    
Traceback (most recent call last):                                              
  File "./build/test-multi-pow", line 47, in call_dcurl                         
    trytes = TryteString(ret[:2673])                                            
TypeError: 'NoneType' object is not subscriptable 
```
and then type ctrl+c

```
Traceback (most recent call last):                                            
  File "./build/test-multi-pow", line 80, in <module>                           
    testing()                                                                   
  File "./build/test-multi-pow", line 71, in testing                            
    while join_list[i].locked(): pass                                           
KeyboardInterrupt                                                               
mk/common.mk:27: recipe for target 'build/test-multi-pow.done' failed           
make: *** [build/test-multi-pow.done] Interrupt                                 
make: *** Deleting intermediate file 'build/test-trinary.o'                     
make: *** Deleting intermediate file 'build/test-curl.o'                        
make: *** Deleting intermediate file 'build/test-dcurl.o'  
```

**Comment by ajblane** [comment]
demsg messages
```
[  153.946346] curl_ctrl_open                                                                    
[  153.946366] curl_idata_dev_open                                                               
[  153.946381] curl_odata_dev_open                                                               
[  153.946632] curl_idata_dev_write begin                                                        
[  153.946642] curl_idata_dev_write end                                                          
[  153.946646] curl_ctrl_dev_write begin                                                         
[  153.946650] curl_ctrl_dev_write end                                                           
[  153.946656] curl_ctrl_read begin                                                              
[  153.947611] Get interrupt                                                                     
[  153.950253] hash_cnt = 28252                                                                  
[  153.950258] tick_cnt = 83748                                                                  
[  153.950260] curl_ctrl_read end                                                                
[  153.950264] curl_odata_dev_read begin                                                         
[  153.950269] curl_odata_dev_read end                                                           
[  153.950310] curl_idata_dev_release                                                            
[  153.950319] curl_odata_dev_release                                                            
[  153.950325] curl_ctrl_release                                                                 
[  158.147717] curl_ctrl_open                                                                    
[  158.147736] curl_idata_dev_open                                                               
[  158.147748] curl_odata_dev_open                                                               
[  158.153566] curl_idata_dev_write begin                                                        
[  158.153578] curl_idata_dev_write end                                                          
[  158.153585] curl_ctrl_dev_write begin                                                         
[  158.153588] curl_ctrl_dev_write end                                                           
[  158.153593] curl_ctrl_read begin                                                              
[  158.245599] Get interrupt                                                                     
[  158.248235] hash_cnt = 3099768                                                                
[  158.248239] tick_cnt = 9188599                                                                
[  158.248242] curl_ctrl_read end                                                                
[  158.248250] curl_odata_dev_read begin                                                         
[  158.248255] curl_odata_dev_read end                                                           
[  158.248522] curl_idata_dev_write begin                                                        
[  158.248535] curl_idata_dev_write end                                                          
[  158.248540] curl_ctrl_dev_write begin                                                         
[  158.248543] curl_ctrl_dev_write end                                                           
[  158.248548] curl_ctrl_read begin                                                              
[  158.299416] Get interrupt                                                                     
[  158.302058] hash_cnt = 1712004                                                                
[  158.302063] tick_cnt = 5074870                                                                
[  158.302065] curl_ctrl_read end                                                                
[  158.302076] curl_odata_dev_read begin                                                         
[  158.302081] curl_odata_dev_read end                                                           
[  158.302345] curl_idata_dev_write begin                                                        
[  158.302357] curl_idata_dev_write end                                                          
[  158.302363] curl_ctrl_dev_write begin                                                         
[  158.302366] curl_ctrl_dev_write end                                                           
[  158.302371] curl_ctrl_read begin                                                              
[  158.401788] Get interrupt                                                                     
[  158.404439] hash_cnt = 3349696                                                                
[  158.404443] tick_cnt = 9929457                                                                
[  158.404446] curl_ctrl_read end                                                                
[  158.404458] curl_odata_dev_read begin                                                         
[  158.404463] curl_odata_dev_read end                                                           
[  158.404841] curl_idata_dev_write begin                                                        
[  158.404854] curl_idata_dev_write end                                                          
[  158.404860] curl_ctrl_dev_write begin                                                         
[  158.404864] curl_ctrl_dev_write end                                                           
[  158.404869] curl_ctrl_read begin                                                              
[  158.524062] Get interrupt                                                                     
[  158.526737] hash_cnt = 4016936                                                                
[  158.526741] tick_cnt = 11907347                                                               
[  158.526744] curl_ctrl_read end                                                                
[  158.526755] curl_odata_dev_read begin                                                         
[  158.526760] curl_odata_dev_read end                                                           
[  158.527228] curl_idata_dev_write begin                                                        
[  158.527244] curl_idata_dev_write end                                                          
[  158.527250] curl_ctrl_dev_write begin                                                         
[  158.527254] curl_ctrl_dev_write end                                                           
[  158.527259] curl_ctrl_read begin                                                              
[  158.578763] Get interrupt                                                                     
[  158.581402] hash_cnt = 1733452                                                                
[  158.581406] tick_cnt = 5138448                                                                
[  158.581409] curl_ctrl_read end                                                                
[  158.581418] curl_odata_dev_read begin                                                         
[  158.581423] curl_odata_dev_read end                                                           
[  158.581688] curl_idata_dev_write begin                                                        
[  158.581700] curl_idata_dev_write end                                                          
[  158.581706] curl_ctrl_dev_write begin                                                         
[  158.581709] curl_ctrl_dev_write end                                                           
[  158.581714] curl_ctrl_read begin                                                              
[  158.639520] Get interrupt                                                                     
[  158.642162] hash_cnt = 1946056                                                                
[  158.642166] tick_cnt = 5768667                                                                
[  158.642169] curl_ctrl_read end                                                                
[  158.642179] curl_odata_dev_read begin                                                         
[  158.642185] curl_odata_dev_read end                                                           
[  158.642737] curl_idata_dev_write begin                                                        
[  158.642751] curl_idata_dev_write end                                                          
[  158.642757] curl_ctrl_dev_write begin                                                         
[  158.642761] curl_ctrl_dev_write end                                                           
[  158.642766] curl_ctrl_read begin                                                              
[  158.748756] Get interrupt                                                                     
[  158.751405] hash_cnt = 3571456                                                                
[  158.751410] tick_cnt = 10586817                                                               
[  158.751413] curl_ctrl_read end                                                                
[  158.751424] curl_odata_dev_read begin                                                         
[  158.751429] curl_odata_dev_read end                                                           
[  161.993874] curl_odata_dev_release                                                            
[  161.993885] curl_idata_dev_release                                                            
[  161.993891] curl_ctrl_release
```
